spring:
  application:
    name: PracticeMicroservice
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: 
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
