spring:
  application:
    name: consumer
  kafka:
    consumer:
      bootstrap-server: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer


server:
  port: 9091
